/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ProjectIndexLazyImport = createFileRoute('/project/')()
const ProjectProjectIdIndexLazyImport = createFileRoute(
  '/project/$projectId/',
)()
const ProjectProjectIdServiceServiceIdLazyImport = createFileRoute(
  '/project/$projectId/service/$serviceId',
)()
const ProjectProjectIdServiceCreateIndexLazyImport = createFileRoute(
  '/project/$projectId/service/create/',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ProjectIndexLazyRoute = ProjectIndexLazyImport.update({
  path: '/project/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/project/index.lazy').then((d) => d.Route))

const ProjectProjectIdIndexLazyRoute = ProjectProjectIdIndexLazyImport.update({
  path: '/project/$projectId/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/project/$projectId/index.lazy').then((d) => d.Route),
)

const ProjectProjectIdServiceServiceIdLazyRoute =
  ProjectProjectIdServiceServiceIdLazyImport.update({
    path: '/project/$projectId/service/$serviceId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/project/$projectId/service/$serviceId.lazy').then(
      (d) => d.Route,
    ),
  )

const ProjectProjectIdServiceCreateIndexLazyRoute =
  ProjectProjectIdServiceCreateIndexLazyImport.update({
    path: '/project/$projectId/service/create/',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/project/$projectId/service/create/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectId/service/$serviceId': {
      id: '/project/$projectId/service/$serviceId'
      path: '/project/$projectId/service/$serviceId'
      fullPath: '/project/$projectId/service/$serviceId'
      preLoaderRoute: typeof ProjectProjectIdServiceServiceIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/project/$projectId/service/create/': {
      id: '/project/$projectId/service/create/'
      path: '/project/$projectId/service/create'
      fullPath: '/project/$projectId/service/create'
      preLoaderRoute: typeof ProjectProjectIdServiceCreateIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ProjectIndexLazyRoute,
  ProjectProjectIdIndexLazyRoute,
  ProjectProjectIdServiceServiceIdLazyRoute,
  ProjectProjectIdServiceCreateIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/project/",
        "/project/$projectId/",
        "/project/$projectId/service/$serviceId",
        "/project/$projectId/service/create/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/project/": {
      "filePath": "project/index.lazy.tsx"
    },
    "/project/$projectId/": {
      "filePath": "project/$projectId/index.lazy.tsx"
    },
    "/project/$projectId/service/$serviceId": {
      "filePath": "project/$projectId/service/$serviceId.lazy.tsx"
    },
    "/project/$projectId/service/create/": {
      "filePath": "project/$projectId/service/create/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
